version: "3.8"

services:
  frontend:
    build: 
      context: ./dev-collab-frontend
    volumes:
      - ./dev-collab-frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev

  backend:
    build: ./dev-collab-backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/devcollab
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - db
      - ai

  ai:
    build: ./ai-service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=devcollab
      - DATABASE_URL=postgresql://user:password@db:5432/dbname

    ports:
      - "5432:5432"

volumes:
  frontend_node_modules: